stages:
  - build
  - test
  - lint

variables:
  GIT_SUBMODULE_STRATEGY: recursive

default:
  before_script:
    - mkdir -p ~/.local/bin
    - export PATH=$HOME/.local/bin:$PATH
    - curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - stack install yesod-bin --install-ghc

build:
  stage: build
  script: stack build

test: 
  stage: test
  script: stack --no-terminal --skip-ghc-check test

lint:
  stage: lint
  script: hlint lint app/ config/ src/ static/ templates/ test/
